version: "3"

services: 
    mysql:
        image: mysql
        container_name: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app_db
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        environment: 
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "8080:80"
    web:
        container_name: laravel
        build: .
        links: 
            - mysql
        volumes: 
            - ./app:/app
        ports:
            - "8000:8000"
        command: php artisan serve --host=0.0.0.0 --port=8000

volumes: 
    dbdata:
